//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LEILAO
    {
        public int ID_LEILAO { get; set; }
        public string DS_NOME_LEILAO { get; set; }
        public double VL_INICIAL { get; set; }
        public bool FL_PRODUTO_USUADO { get; set; }
        public int ID_USUARIO_RESPONSAVEL { get; set; }
        public System.DateTime DT_ABERTURA { get; set; }
        public System.DateTime DT_FINALIZACAO { get; set; }
    
        public virtual TB_USUARIO TB_USUARIO { get; set; }
    }
}
